In [3]:
import numpy as np
x= np.array([10,20,30,40,50])
print(x,type(x))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [45]:
y=np.array(([1,2],[3,4],[5,6]))
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [3]:
import numpy as np
a= np.array([7,8,9],dtype = float)
print(a,a.dtype)


[7. 8. 9.] float64


In [53]:
print(np.zeros(6))

[0. 0. 0. 0. 0. 0.]


In [55]:
print(np.ones((3,2)))


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [57]:
print(np.empty((2,2)))


[[2.12199579e-314 6.74794662e-312]
 [4.54540394e-321 6.74794662e-312]]


In [33]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [41]:
np.random.random((3,3))

array([[0.07942229, 0.85008898, 0.54180994],
       [0.91223306, 0.49692287, 0.17539403],
       [0.61007223, 0.93136433, 0.5568585 ]])