In [4]:
import numpy as np
np.random.seed(1)
x=np.random.randint(0,10,size=5)
x.sort()
print(x)

[0 5 5 8 9]


In [10]:
i = np.argsort(x)
print(i)
print(x[i])

[0 1 2 3 4]
[0 5 5 8 9]


In [20]:
np.random.seed(1)
x=np.random.randint(0,30,size=(4,6))
print(x)
a=np.sort(x,axis=1)
print(a)
b=np.sort(x,axis=0)
print(b)

[[ 5 11 12  8  9 11]
 [ 5 15  0 16  1 12]
 [ 7 13 28  6 25 18]
 [20  5 18 20 11 28]]
[[ 5  8  9 11 11 12]
 [ 0  1  5 12 15 16]
 [ 6  7 13 18 25 28]
 [ 5 11 18 20 20 28]]
[[ 5  5  0  6  1 11]
 [ 5 11 12  8  9 12]
 [ 7 13 18 16 11 18]
 [20 15 28 20 25 28]]


In [26]:
np.random.seed(1)
x=np.random.randint(0,30,size=15)
print(x)
q= np.partition(x,4)
print(q)
x.sort()
print(x)

[ 5 11 12  8  9 11  5 15  0 16  1 12  7 13 28]
[ 5  0  1  5  7  8  9 11 11 13 12 12 15 16 28]
[ 0  1  5  5  7  8  9 11 11 12 12 13 15 16 28]


In [36]:
a=np.array(['ram','sam','ray','snow'])
b=np.array([51,67,89,43])
y= np.argsort(b)
c=a[y]
print(c)

['snow' 'ram' 'sam' 'ray']


In [38]:
np.random.seed(1)
x=np.random.randint(0,3,size=(10,2))
dist_sq = np.sum((x[:, np.newaxis, :] - x[np.newaxis, :, :]) ** 2, axis=-1)
t= np.argsort(dist_sq, axis=1)
print(t)

[[0 2 9 1 3 4 6 8 5 7]
 [1 3 4 5 7 9 0 2 6 8]
 [0 2 9 1 3 4 6 8 5 7]
 [1 3 4 5 7 9 0 2 6 8]
 [1 3 4 5 7 9 0 2 6 8]
 [5 7 1 3 4 6 8 9 0 2]
 [6 8 5 7 1 3 4 0 2 9]
 [5 7 1 3 4 6 8 9 0 2]
 [6 8 5 7 1 3 4 0 2 9]
 [9 0 1 2 3 4 5 7 6 8]]


In [64]:
title = ['Harry Potter', 'Mystery Tales','Ramayana','Mahabharat']
author = ['JK Rowling','Raj','valmiki','Max']
price =[356,457, 124,367]
book= np.zeros(4,dtype={'names':['title','author','price'], 'formats':['U30','U20','f4']})
book['title'] = title
book['author'] = author
book['price'] = price
print(book)


[('Harry Potter', 'JK Rowling', 356.) ('Mystery Tales', 'Raj', 457.)
 ('Ramayana', 'valmiki', 124.) ('Mahabharat', 'Max', 367.)]


In [68]:
book['title']

array(['Harry Potter', 'Mystery Tales', 'Ramayana', 'Mahabharat'],
      dtype='<U30')