In [4]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(20,)
20
int32


In [10]:
np.random.seed(42)
arr = np.random.randint(0, 50, size=(4, 5))
print(arr)
print(arr.itemsize)
print(arr.nbytes)

[[38 28 14 42  7]
 [20 38 18 22 10]
 [10 23 35 39 23]
 [ 2 21  1 23 43]]
4
80


In [12]:
arr = np.arange(1, 13).reshape(3, 4)
sub_arr = arr[:2, :2]
print(sub_arr)

[[1 2]
 [5 6]]


In [20]:
sub_arr1=arr[:,::2]
print(sub_arr1)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [22]:
sub_arr2=arr[:,::-1]
print(sub_arr2)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [26]:
sub_arr3=arr[1,:]
print(sub_arr3)

[5 6 7 8]


In [30]:
sub_arr1=arr[2,3]
print(sub_arr1)

12


In [34]:
sub_arr4=arr[-1,:]
print(sub_arr4)

[ 9 10 11 12]


In [36]:
sub_arr5=arr[:,-1]
print(sub_arr5)

[ 4  8 12]


In [42]:
x = np.arange(1, 13).reshape(3, 4)
print(x)
np.reshape(x,(12,1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [52]:
x=np.arange(1, 13).reshape(3, 4)
x[:,np.newaxis]

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [62]:
arr = np.random.randint(0, 20, size=(2, 3))
x= np.random.randint(0, 20, size=(2, 3))
x1=np.vstack([arr,x])
x2=np.hstack([arr,x])
x3=np.concatenate([arr,x],axis=1)
print(x1)
print(x2)
print(x3)

[[15 14  7]
 [13  7 15]
 [12 17 14]
 [12  8 14]]
[[15 14  7 12 17 14]
 [13  7 15 12  8 14]]
[[15 14  7 12 17 14]
 [13  7 15 12  8 14]]


In [72]:
a= np.arange(0,15)
x1,x2,x3=np.split(a,3)
print(x1)
print(x2)
print(x3)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


In [3]:
import numpy as np
arr = np.arange(1, 25).reshape(6, 4)
a1,a2 = np.hsplit(arr, 2)
b1,b2 = np.vsplit(arr, 2)
print (a1)
print (a2)
print (b1)
print (b2)

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]
 [21 22]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]
 [19 20]
 [23 24]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
